### ISSUE TITLE
SMMP11: log input pixels & cpu

### ISSUE THREAD

**Issue by jdries** [eu-cdse/openeo-cdse-infra#19]
SMMP11 should record openEO processing volume. The definition is not super clear, so I would log both 'input pixels' and cpu hours. Tracking both indicators gives a better picture of what is going on.

Better idea: get cpu and network received from prometheus.

**Comment by JeroenVerstraelen** [comment]
- CPU Hours
https://prometheus.openeo-cdse-prod.vgt.vito.be/api/v1/query?query=sum(increase(container_cpu_usage_seconds_total%7Bnamespace%3D%22spark-jobs-prod%22%7D%5B2h%5D))
Will show the increase in cpu seconds over the last 2 hour period.
- Input pixels
https://prometheus.openeo-cdse-prod.vgt.vito.be/api/v1/query?query=sum(increase(container_network_receive_bytes_total%7Bnamespace%3D%22spark-jobs-prod%22%7D%5B2h%5D))
Will show the increase in received bytes over the last 2 hour period.

@jdries The Nifi flows to publish these values to Sinergise are ready. I just have a few more questions:  
- What metric and product name does Sinergise expect for these metrics? For example:
metric name: kpi06__vito__open_eo_availability
product name: openeo
- What unit should be used for the values?
I will translate cpu seconds to hours, should bytes be translated?
- What periods should be used?
Currently we are aggregating over the last 2 hours.
- How often should we publish?
kpi06__vito__open_eo_availability is published every two minutes.

**Comment by JanssenBrm** [comment]
The name of the metric should be set to `smmp11__vito__oeo_proc_vol`

**Comment by JeroenVerstraelen** [comment]
Note:
The nifi flows can be found on the nifi cluster under:
CDSE/KPI Monitorring/OPENEO CDSE KPIs

Status update:
An email was sent to Sinergise. I believe we decided to send 2 values for the smmp11__vito__oeo_proc_vol metric. @jdries is this correct? We currently have a pretty generic nifi flow that only allows us to send 1 value per metric, so that would need to be adjusted first.
The aggregation period, metric units, and publish frequency are still to be decided.

**Comment by jdries** [comment]
Short term solution: log cpu only, 
units: cpu hours
frequency: hourly

**Comment by jdries** [comment]
done, all metrics are being sent to api
