### ISSUE TITLE
CDSE benchmark suite

### ISSUE THREAD

**Issue by jdries** [eu-cdse/openeo-cdse-infra#4]
Define a basic benchmark suite for CDSE, similar to marketplace benchmarks.

**Comment by JeroenVerstraelen** [comment]
Update:
The benchmarks nifi flow is ready on the nifi cluster under /CDSE/benchmarks. There benchmarks are currently blocked however by this error:
```
openeo.rest.OpenEoRestError: Got status code 200 for `POST /jobs` (expected [201]) with body <html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 9168897901493726888<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```
A jira ticket has been opened on [cloudferro](https://jira.cloudferro.com/browse/CDSE-45), once that is resolved the benchmarks can be enabled again.

**Comment by JeroenVerstraelen** [comment]
The benchmarks are now enabled, they run every day at 4 AM and 5 AM.

Notes:
- Using openeo.creo.vito.be endpoint to circumvent the WAF issues
- Removed job_options because it causes issues when starting the driver on CDSE: 
Open-EO/openeo-geopyspark-driver#461
- Using SENTINEL2_L1C instead of SENTINEL1_GRD because the default sar_backscatter_coefficient is not supported on CDSE
open-EO/openeo-geopyspark-driver#311

**Comment by JeroenVerstraelen** [comment]
The benchmarks can be found on [Kibana](https://kibana-apps.vgt.vito.be/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(columns:!(created,finished,backend_id,user_id,job_id,status,title,description),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8b3ab910-ea78-11ed-9c26-3f76720e6a27',key:description,negate:!f,params:(query:benchmarking-creo),type:phrase),query:(match:(description:(query:benchmarking-creo,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8b3ab910-ea78-11ed-9c26-3f76720e6a27',key:user_id,negate:!f,params:(query:cdse-ci-service-account),type:phrase),query:(match:(user_id:(query:cdse-ci-service-account,type:phrase))))),index:'8b3ab910-ea78-11ed-9c26-3f76720e6a27',interval:auto,query:(language:kuery,query:''),savedQuery:'CDSE%20Benchmarks',sort:!(!(created,desc)))). We still need to create a Grafana dashboard.

**Comment by jdries** [comment]
Fixed one benchmark where driver was going OOM because it wrote a raster to JSON. 
The kibana view is not yet the right one because it doesn't contain usage info. This info is in the marketplace index.

**Comment by JeroenVerstraelen** [comment]
- Fixed a bug in the timeseries benchmarks
- There is an issue when setting up the grafana dashboard because the Elastic Stack on CDSE has version 7.5.1 while grafana does not support any version under 7.10.0
- I set up a kibana dashboard instead that shows the timeseries data for CPU, Memory and duration for every benchmark

[Kibana dashboard](https://kibana-1.prod.warsaw.marketplace.dataspace.copernicus.eu/app/kibana#/dashboard/cca42db0-2186-11ee-8091-1bebee325886)
